const basics = {
  colors: {
    black: '#000000',
    blackRed: '#420f0f',
    white: '#ffffff',
    creamWhite: '#FFFEFC',
    bloodRed: '#800020',
    fadedRed: '#AA6969',
    solidBlue: '#2844A0',
    neonBlue: '#002FAD',
    fadedBlue: '#9EADD5',
    chalkBlue: '#727884',
    soapBlue: '#425bc2',
    washBlue: '#EDFCFF',
    solidGreen: '#247013',
    washGreen: '#dcffd4',
    deepGreen: '#194f0d',
    yellow: '#FFF11B',
    washOrange: '#fff8eb',
    citrus: '#E0861F',
    chalkRed: '#C1B6B6',
    chalk: '#bababa',
    deepRed: '#650019',
    deepBlue: '#010D4E',
    rose: '#AA405B',
    pink: '#DBA3B1',
    paper: '#FAFAC8',
    wood: '#855E42',
    nightShift: '#D1D1C0',
    chocolate: '#9e4e15',
  },
  transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
  fonts: {
    Montserrat: "'Montserrat', sans-serif",
    RadioCanada: "'Radio Canada', sans-serif",
    Mulish: "'Mulish', sans-serif",
    RobotoFlex: "'Roboto Flex', sans-serif",
  },
  fontSize: {
    large: '44px',
    xlarge: '72px',
    xxlarge: '100px',
    small: '16px',
    xsmall: '13px',
    xxsmall: '11px',
    medium: '22px',
  },
};

export default basics;
